### ISSUE TITLE
thread 'main' panicked at src/pwnodeobject.rs:331:67:

### ISSUE THREAD

**Issue by mxmilkiib** [saivert/pwvucontrol#5]
I'm getting a crash on start;

```
23:34:30 milk@red:~/tmp/pwvucontrol main ± pwvucontrol 
I 23:34:34.604232            wp-core ../wireplumber/lib/wp/core.c:183:core_info: <WpCore:0x56355ad59310> connected to server: pipewire-0, cookie: 718177540
I 23:34:34.636607          wp-plugin ../wireplumber/lib/wp/plugin.c:125:wp_plugin_activate_execute_step: <WpMixerApi:0x56355ad603b0> enabling plugin 'mixer-api'
I 23:34:34.638617                    src/manager.rs:238:: added metadata object: 39
I 23:34:34.638643                    src/manager.rs:242:: Metadata value: 0, "default.configured.audio.sink", "Spa:String:JSON", "{\"name\":\"alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0\"}"
I 23:34:34.638668                    src/manager.rs:242:: Metadata value: 0, "default.configured.audio.source", "Spa:String:JSON", "{\"name\":\"alsa_input.usb-ZOOM_Corporation_H6_000000000000-00.analog-stereo\"}"
I 23:34:34.638680                    src/manager.rs:242:: Metadata value: 36, "target.node", "Spa:Id", "37"
I 23:34:34.638696                    src/manager.rs:242:: Metadata value: 0, "default.audio.sink", "Spa:String:JSON", "{\"name\":\"alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0\"}"
I 23:34:34.638711                    src/manager.rs:242:: Metadata value: 0, "default.audio.source", "Spa:String:JSON", "{\"name\":\"alsa_input.pci-0000_00_1f.3.analog-stereo\"}"
I 23:34:34.638726                    src/manager.rs:242:: Metadata value: 0, "default.video.source", "Spa:String:JSON", "{\"name\":\"v4l2_input.pci-0000_00_14.0-usb-0_8_1.0\"}"
I 23:34:34.643847                    src/manager.rs:199:: Activated plugin mixer-api
I 23:34:34.643872          wp-plugin ../wireplumber/lib/wp/plugin.c:125:wp_plugin_activate_execute_step: <WpDefaultNodesApi:0x56355ad617c0> enabling plugin 'default-nodes-api'
I 23:34:34.644493                    src/manager.rs:199:: Activated plugin default-nodes-api
I 23:34:34.644616                    src/manager.rs:152:: added: Some("audiorelay_source")
I 23:34:34.654650                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.654746                    src/output_dropdown.rs:126:: selected-item
I 23:34:34.656340                    src/manager.rs:152:: added: Some("audiorelay_Speaker")
I 23:34:34.658871                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.660060                    src/manager.rs:161:: Got device 50 alsa_card.pci-0000_01_00.1
I 23:34:34.660087                    src/manager.rs:161:: Got device 51 alsa_card.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032199-00
I 23:34:34.660102                    src/manager.rs:161:: Got device 52 alsa_card.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00
I 23:34:34.660118                    src/manager.rs:161:: Got device 53 alsa_card.pci-0000_00_1f.3
I 23:34:34.660143                    src/manager.rs:152:: added: Some("alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032199-00.pro-output-0")
I 23:34:34.667089                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.678025                    src/manager.rs:152:: added: Some("alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0")
I 23:34:34.684393                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.685678                    src/manager.rs:152:: added: Some("alsa_output.pci-0000_00_1f.3.analog-stereo")
I 23:34:34.688263                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.689535                    src/manager.rs:152:: added: Some("Firefox")
I 23:34:34.693757                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.693857                    src/output_dropdown.rs:126:: selected-item
I 23:34:34.709321                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.709618                    src/output_dropdown.rs:126:: selected-item
I 23:34:34.709648                    src/outputbox.rs:143:: switching to preferred target pos=0 boundid=37 serial=37
I 23:34:34.709704                    src/output_dropdown.rs:126:: selected-item
I 23:34:34.709740                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.709762                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.709787                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.709819                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.709833                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710062                    src/output_dropdown.rs:126:: selected-item
I 23:34:34.710111                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710335                    src/outputbox.rs:143:: switching to preferred target pos=0 boundid=37 serial=37
I 23:34:34.710368                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710395                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710424                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710463                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710494                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710708                    src/output_dropdown.rs:126:: selected-item
I 23:34:34.710754                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.710972                    src/outputbox.rs:143:: switching to preferred target pos=0 boundid=37 serial=37
I 23:34:34.711003                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.711034                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.711063                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.711092                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.711123                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:34:34.711333                    src/output_dropdown.rs:126:: selected-item
thread 'main' panicked at src/pwnodeobject.rs:331:67:
Rate!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
23:34:34 milk@red:~/tmp/pwvucontrol main 101 ± RUST_BACKTRACE=1 pwvucontrol 
I 23:35:42.559378            wp-core ../wireplumber/lib/wp/core.c:183:core_info: <WpCore:0x55e32be7de00> connected to server: pipewire-0, cookie: 718177540
I 23:35:42.603333          wp-plugin ../wireplumber/lib/wp/plugin.c:125:wp_plugin_activate_execute_step: <WpMixerApi:0x55e32be35380> enabling plugin 'mixer-api'
I 23:35:42.605471                    src/manager.rs:238:: added metadata object: 39
I 23:35:42.605491                    src/manager.rs:242:: Metadata value: 0, "default.configured.audio.sink", "Spa:String:JSON", "{\"name\":\"alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0\"}"
I 23:35:42.605505                    src/manager.rs:242:: Metadata value: 0, "default.configured.audio.source", "Spa:String:JSON", "{\"name\":\"alsa_input.usb-ZOOM_Corporation_H6_000000000000-00.analog-stereo\"}"
I 23:35:42.605513                    src/manager.rs:242:: Metadata value: 36, "target.node", "Spa:Id", "37"
I 23:35:42.605522                    src/manager.rs:242:: Metadata value: 0, "default.audio.sink", "Spa:String:JSON", "{\"name\":\"alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0\"}"
I 23:35:42.605531                    src/manager.rs:242:: Metadata value: 0, "default.audio.source", "Spa:String:JSON", "{\"name\":\"alsa_input.pci-0000_00_1f.3.analog-stereo\"}"
I 23:35:42.605539                    src/manager.rs:242:: Metadata value: 0, "default.video.source", "Spa:String:JSON", "{\"name\":\"v4l2_input.pci-0000_00_14.0-usb-0_8_1.0\"}"
I 23:35:42.611005                    src/manager.rs:199:: Activated plugin mixer-api
I 23:35:42.611034          wp-plugin ../wireplumber/lib/wp/plugin.c:125:wp_plugin_activate_execute_step: <WpDefaultNodesApi:0x55e32be42f90> enabling plugin 'default-nodes-api'
I 23:35:42.611718                    src/manager.rs:199:: Activated plugin default-nodes-api
I 23:35:42.611863                    src/manager.rs:152:: added: Some("audiorelay_source")
I 23:35:42.621470                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:35:42.621592                    src/output_dropdown.rs:126:: selected-item
I 23:35:42.624034                    src/manager.rs:152:: added: Some("audiorelay_Speaker")
I 23:35:42.626747                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:35:42.627991                    src/manager.rs:161:: Got device 50 alsa_card.pci-0000_01_00.1
I 23:35:42.628010                    src/manager.rs:161:: Got device 51 alsa_card.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032199-00
I 23:35:42.628026                    src/manager.rs:161:: Got device 52 alsa_card.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00
I 23:35:42.628039                    src/manager.rs:161:: Got device 53 alsa_card.pci-0000_00_1f.3
I 23:35:42.628067                    src/manager.rs:152:: added: Some("alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032199-00.pro-output-0")
I 23:35:42.630482                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:35:42.649317                    src/manager.rs:152:: added: Some("alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0")
I 23:35:42.652437                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:35:42.653692                    src/manager.rs:152:: added: Some("alsa_output.pci-0000_00_1f.3.analog-stereo")
I 23:35:42.656350                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:35:42.657837                    src/manager.rs:152:: added: Some("Firefox")
I 23:35:42.661824                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:35:42.661922                    src/output_dropdown.rs:126:: selected-item
thread 'main' panicked at src/pwnodeobject.rs:331:67:
Rate!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:178:5
   3: core::panicking::panic_str
             at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/option.rs:1979:5
   5: wireplumber::auto::pipewire_object::PipewireObjectExt::enum_params::enum_params_trampoline
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: g_closure_invoke
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: g_main_context_iteration
  22: g_application_run
  23: gio::application::ApplicationExtManual::run
  24: pwvucontrol::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
```
23:35:44 milk@red:~/tmp/pwvucontrol main 101 ± RUST_BACKTRACE=full pwvucontrol 
I 23:37:27.293623            wp-core ../wireplumber/lib/wp/core.c:183:core_info: <WpCore:0x56512fa00290> connected to server: pipewire-0, cookie: 718177540
I 23:37:27.335381          wp-plugin ../wireplumber/lib/wp/plugin.c:125:wp_plugin_activate_execute_step: <WpMixerApi:0x56512f9c5070> enabling plugin 'mixer-api'
I 23:37:27.335974                    src/manager.rs:238:: added metadata object: 39
I 23:37:27.335991                    src/manager.rs:242:: Metadata value: 0, "default.configured.audio.sink", "Spa:String:JSON", "{\"name\":\"alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0\"}"
I 23:37:27.336003                    src/manager.rs:242:: Metadata value: 0, "default.configured.audio.source", "Spa:String:JSON", "{\"name\":\"alsa_input.usb-ZOOM_Corporation_H6_000000000000-00.analog-stereo\"}"
I 23:37:27.336010                    src/manager.rs:242:: Metadata value: 36, "target.node", "Spa:Id", "37"
I 23:37:27.336018                    src/manager.rs:242:: Metadata value: 0, "default.audio.sink", "Spa:String:JSON", "{\"name\":\"alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0\"}"
I 23:37:27.336033                    src/manager.rs:242:: Metadata value: 0, "default.audio.source", "Spa:String:JSON", "{\"name\":\"alsa_input.pci-0000_00_1f.3.analog-stereo\"}"
I 23:37:27.336046                    src/manager.rs:242:: Metadata value: 0, "default.video.source", "Spa:String:JSON", "{\"name\":\"v4l2_input.pci-0000_00_14.0-usb-0_8_1.0\"}"
I 23:37:27.342681                    src/manager.rs:199:: Activated plugin mixer-api
I 23:37:27.342710          wp-plugin ../wireplumber/lib/wp/plugin.c:125:wp_plugin_activate_execute_step: <WpDefaultNodesApi:0x56512f9ba790> enabling plugin 'default-nodes-api'
I 23:37:27.343406                    src/manager.rs:199:: Activated plugin default-nodes-api
I 23:37:27.343537                    src/manager.rs:152:: added: Some("audiorelay_source")
I 23:37:27.353440                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:37:27.353531                    src/output_dropdown.rs:126:: selected-item
I 23:37:27.355678                    src/manager.rs:152:: added: Some("audiorelay_Speaker")
I 23:37:27.358347                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:37:27.359595                    src/manager.rs:161:: Got device 50 alsa_card.pci-0000_01_00.1
I 23:37:27.359615                    src/manager.rs:161:: Got device 51 alsa_card.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032199-00
I 23:37:27.359631                    src/manager.rs:161:: Got device 52 alsa_card.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00
I 23:37:27.359644                    src/manager.rs:161:: Got device 53 alsa_card.pci-0000_00_1f.3
I 23:37:27.359673                    src/manager.rs:152:: added: Some("alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032199-00.pro-output-0")
I 23:37:27.362520                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:37:27.372324                    src/manager.rs:152:: added: Some("alsa_output.usb-AudioQuest_AudioQuest_DragonFly_Cobalt_v1.0_AQDFCB0101032045-00.pro-output-0")
I 23:37:27.378638                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:37:27.381555                    src/manager.rs:152:: added: Some("alsa_output.pci-0000_00_1f.3.analog-stereo")
I 23:37:27.388122                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:37:27.390869                    src/manager.rs:152:: added: Some("Firefox")
I 23:37:27.402377                    src/volumebox/mod.rs:168:: default-nodes-api changed: new id 67
I 23:37:27.402654                    src/output_dropdown.rs:126:: selected-item
thread 'main' panicked at src/pwnodeobject.rs:331:67:
Rate!
stack backtrace:
   0:     0x56512f0e777c - std::backtrace_rs::backtrace::libunwind::trace::h1c0d6c1feff90834
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56512f0e777c - std::backtrace_rs::backtrace::trace_unsynchronized::he4dc4a997c5ae9a3
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56512f0e777c - std::sys_common::backtrace::_print_fmt::h5a4f8cab839a8801
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56512f0e777c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h633d15e63f261bac
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56512f10c590 - core::fmt::rt::Argument::fmt::h7bd3372d26ac29ee
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/fmt/rt.rs:142:9
   5:     0x56512f10c590 - core::fmt::write::h81c224801dea0c8c
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/fmt/mod.rs:1117:17
   6:     0x56512f0e594f - std::io::Write::write_fmt::h5d5fd4c0f9d7aaa2
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/io/mod.rs:1763:15
   7:     0x56512f0e7564 - std::sys_common::backtrace::_print::hae2beb76b35b9dac
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56512f0e7564 - std::sys_common::backtrace::print::hbc2e16b509b271b5
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56512f0e8a77 - std::panicking::default_hook::{{closure}}::hdd572dcbcaa64ada
  10:     0x56512f0e87df - std::panicking::default_hook::h3f7cc4d3b39ae3db
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:292:9
  11:     0x56512f0e8ef8 - std::panicking::rust_panic_with_hook::hd2051524a5282492
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:779:13
  12:     0x56512f0e8dde - std::panicking::begin_panic_handler::{{closure}}::h699c051ec6e2b537
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:657:13
  13:     0x56512f0e7c46 - std::sys_common::backtrace::__rust_end_short_backtrace::h5d4269c5675c7d12
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56512f0e8b42 - rust_begin_unwind
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:645:5
  15:     0x56512f060055 - core::panicking::panic_fmt::hd8a918fb3507036f
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:72:14
  16:     0x56512f060013 - core::panicking::panic_display::hd9174eb804bc846e
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:178:5
  17:     0x56512f060013 - core::panicking::panic_str::h246e559cd54db345
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:152:5
  18:     0x56512f060013 - core::option::expect_failed::h605f57acd33fb746
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/option.rs:1979:5
  19:     0x56512f0b28ae - wireplumber::auto::pipewire_object::PipewireObjectExt::enum_params::enum_params_trampoline::hcdcb4d810f506d87
  20:     0x7f3d62bced14 - <unknown>
  21:     0x7f3d62bd2c2d - <unknown>
  22:     0x7f3d62d4a13c - <unknown>
  23:     0x7f3d62ad76c0 - g_closure_invoke
  24:     0x7f3d62d1b76d - <unknown>
  25:     0x7f3d62bced14 - <unknown>
  26:     0x7f3d62bd2c2d - <unknown>
  27:     0x7f3d62d1f999 - <unknown>
  28:     0x7f3d5c4d4623 - <unknown>
  29:     0x7f3d5c4cc162 - <unknown>
  30:     0x7f3d5c4cc940 - <unknown>
  31:     0x7f3d5c963646 - <unknown>
  32:     0x7f3d62d1f5b5 - <unknown>
  33:     0x7f3d629d0f69 - <unknown>
  34:     0x7f3d62a2f327 - <unknown>
  35:     0x7f3d629cf162 - g_main_context_iteration
  36:     0x7f3d62c04b16 - g_application_run
  37:     0x56512f0aa820 - gio::application::ApplicationExtManual::run::h95bf5cf5dd501d9a
  38:     0x56512f077caf - pwvucontrol::main::h79df9693c844696c
  39:     0x56512f0b35b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h49e296b440058f6a
  40:     0x56512f09e519 - std::rt::lang_start::{{closure}}::h91806801bba1a3af
  41:     0x56512f0e1ac7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h771ef532d64e3cf0
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/ops/function.rs:284:13
  42:     0x56512f0e1ac7 - std::panicking::try::do_call::h6b5473cbd2af12b6
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:552:40
  43:     0x56512f0e1ac7 - std::panicking::try::h7d23973be288124d
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:516:19
  44:     0x56512f0e1ac7 - std::panic::catch_unwind::h045b64dbda335fac
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panic.rs:142:14
  45:     0x56512f0e1ac7 - std::rt::lang_start_internal::{{closure}}::h06953691442cccca
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/rt.rs:148:48
  46:     0x56512f0e1ac7 - std::panicking::try::do_call::h06b9dcffb4598b44
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:552:40
  47:     0x56512f0e1ac7 - std::panicking::try::ha2213ba5855e92ce
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:516:19
  48:     0x56512f0e1ac7 - std::panic::catch_unwind::hf41b7dd010a53b79
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panic.rs:142:14
  49:     0x56512f0e1ac7 - std::rt::lang_start_internal::hc0ed1a6a316dd7cd
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/rt.rs:148:20
  50:     0x56512f09e50e - std::rt::lang_start::h345f88fb6f4509f1
  51:     0x7f3d619facd0 - <unknown>
  52:     0x7f3d619fad8a - __libc_start_main
  53:     0x56512f0607b5 - _start
  54:                0x0 - <unknown>
```

**Comment by saivert** [comment]
I see this is due to one of your audio devices not having a sample rate property. Why is that?

**Comment by saivert** [comment]
This is fixed in main branch (not released).
Channels and Sample rate is optional so I just set the values to 0 if not found.
